name: dataset-annotation
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pip
  - pip:
    - fastapi>=0.103.1
    - uvicorn>=0.23.2
    - python-multipart>=0.0.6
    - pydantic>=2.3.0
    - pillow>=10.0.1
    - numpy>=1.26.0
    - pytest>=7.4.2
    - httpx>=0.24.1
    - python-dotenv>=1.0.0
    - google-cloud-firestore>=2.11.1
    - google-cloud-storage>=2.10.0
    - firebase-admin>=6.2.0
