version: '3.8'

services:
  backend:
    build: .
    ports:
      - "8000:8000"
    environment:
      # Set your GCP project ID and bucket here, or ensure they are set in your .env file
      GCP_PROJECT_ID: your-gcp-project-id
      GCP_STORAGE_BUCKET: your-gcp-storage-bucket
      # MongoDB connection string
      MONGO_URI: mongodb://mongodb:27017/mydatabase
    depends_on:
      - mongodb
    volumes:
      - ./service-account-key.json:/app/service-account-key.json:ro
      - ./yolo11n.pt:/app/yolo11n.pt:ro
      - ./datasets:/app/datasets
      - ./pipeline_output:/app/pipeline_output

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
